name: aplikasi_event_kampus
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# ... (versi dan environment, tidak perlu diubah) ...
version: 1.0.0+1

environment:
  sdk: ^3.9.2

# ... (dependencies, tidak perlu diubah) ...
dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# ... (bagian Dart, tidak perlu diubah) ...

# The following section is specific to Flutter packages.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # -----------------------------------------------------------------
  # ANDA MENULISNYA DI SINI:
  # Pastikan INDENTASI/SPASI-nya pas seperti ini.
  assets:
    - assets/images/
  # -----------------------------------------------------------------

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
